version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      QDRANT_URL: http://qdrant:6333
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - qdrant-net

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant-data:/var/lib/qdrant
    ports:
      - "6333:6333"
    networks:
      - qdrant-net
    hostname: qdrant

networks:
  qdrant-net:
    driver: bridge

volumes:
  qdrant-data:
